
import type { Product } from './types';

export const laptopData: Product[] = [
  {
    id: 'legion-pro-7',
    category: 'laptop',
    name: 'Legion Pro 7 Intel',
    price: 265843.0,
    url: 'https://www.lenovo.com/in/en/configurator/cto/index.html?bundleId=83F5CTO1WWIN1',
    imageUrl: 'https://p2-ofp.static.pub/fes/cms/2024/02/12/j5o9zxy1misj0cphm859sox18p19id298285.png',
    dataAiHint: 'gaming laptop',
    specs: [
      { name: 'CPU', value: 'Intel Core Ultra', icon: 'Cpu' },
      { name: 'GPU', value: 'NVIDIA RTX 4080', icon: 'Component' },
      { name: 'RAM', value: '32GB DDR5', icon: 'MemoryStick' },
      { name: 'Storage', value: '2TB SSD', icon: 'HardDrive' },
      { name: 'Display', value: '16" WQXGA', icon: 'Laptop' },
    ],
  },
  {
    id: 'legion-5-15irx9',
    category: 'laptop',
    name: 'Lenovo Legion 5 15IRX9',
    price: 122990.0,
    url: 'https://www.croma.com/lenovo-legion-5-15irx9-intel-core-i7-13th-gen-gaming-laptop-24gb-512gb-ssd-windows-11-home-8gb-graphics-15-6-inch-144-hz-full-hd-ips-display-nvidia-geforce-rtx-4060-ms-office-home-2024-storm-grey-2-32-kg-/p/315212',
    imageUrl: 'https://media-cdn.bnn.in.th/252912/Lenovo-Gaming-Legion-5-15IRX9-i7-14650HX-RTX-4060-1-square_1.jpg',
    dataAiHint: 'gaming laptop',
    specs: [
      { name: 'CPU', value: 'Intel Core i7 13th Gen', icon: 'Cpu' },
      { name: 'GPU', value: 'NVIDIA RTX 4060', icon: 'Component' },
      { name: 'RAM', value: '24GB DDR5', icon: 'MemoryStick' },
      { name: 'Storage', value: '512GB SSD', icon: 'HardDrive' },
      { name: 'Display', value: '15.6" FHD 144Hz', icon: 'Laptop' },
    ],
  },
  {
    id: 'msi-sword-16',
    category: 'laptop',
    name: 'MSI Sword 16 HX',
    price: 139990.0,
    url: 'https://www.croma.com/msi-sword-16-hx-b14vfkg-287in-intel-core-i9-14th-gen-gaming-laptop-16gb-1tb-ssd-windows-11-home-8gb-graphics-16-inch-144-hz-fhd-plusips-level-display-nvidia-geforce-rtx-4060-ms-office-2021-cosmos-gray-2-3-kg-/p/306667',
    imageUrl: 'https://asset.msi.com/resize/image/global/product/product_16964923190a6e053f364070a3e3a44d03d0987180.png/1024.png',
    dataAiHint: 'laptop computer',
    specs: [
      { name: 'CPU', value: 'Intel Core i9 14th Gen', icon: 'Cpu' },
      { name: 'GPU', value: 'NVIDIA RTX 4060', icon: 'Component' },
      { name: 'RAM', value: '16GB DDR5', icon: 'MemoryStick' },
      { name: 'Storage', value: '1TB SSD', icon: 'HardDrive' },
      { name: 'Display', value: '16" FHD+ 144Hz', icon: 'Laptop' },
    ],
  },
  {
    id: 'hp-omen-16-ryzen',
    category: 'laptop',
    name: 'HP Omen 16 xd0020AX',
    price: 104490.0,
    url: 'https://www.croma.com/hp-omen-16-xd0020ax-amd-ryzen-7-gaming-laptop-16gb-1tb-ssd-windows-11-home-8gb-graphics-16-1-inch-165-hz-fhd-display-nvidia-geforce-rtx-4060-ms-office-2021-shadow-black-2-37-kg-/p/307123',
    imageUrl: 'https://in-media.apjonlinecdn.com/catalog/product/cache/b3b166914d87ce343d4dc5ec5117b502/c/0/c08587132_1_1.png',
    dataAiHint: 'omen laptop',
    specs: [
      { name: 'CPU', value: 'AMD Ryzen 7', icon: 'Cpu' },
      { name: 'GPU', value: 'NVIDIA RTX 4060', icon: 'Component' },
      { name: 'RAM', value: '16GB DDR5', icon: 'MemoryStick' },
      { name: 'Storage', value: '1TB SSD', icon: 'HardDrive' },
      { name: 'Display', value: '16.1" FHD 165Hz', icon: 'Laptop' },
    ],
  },
  {
    id: 'lenovo-loq-gen9',
    category: 'laptop',
    name: 'Lenovo LOQ Gen 9',
    price: 94990.0,
    url: 'https://www.lenovo.com/in/en/p/laptops/loq-laptops/lenovo-loq-15arp9/83jc00ehin',
    imageUrl: 'https://p3-ofp.static.pub/fes/cms/2024/04/24/gpl6zxi5yl2o1o4y1wz6pgbfy1w86i867660.png',
    dataAiHint: 'lenovo laptop',
    specs: [
      { name: 'CPU', value: 'AMD Ryzen 7', icon: 'Cpu' },
      { name: 'GPU', value: 'NVIDIA RTX 4050', icon: 'Component' },
      { name: 'RAM', value: '16GB DDR5', icon: 'MemoryStick' },
      { name: 'Storage', value: '512GB SSD', icon: 'HardDrive' },
      { name: 'Display', value: '15.6" FHD', icon: 'Laptop' },
    ],
  },
  {
    id: 'alienware-16-aurora',
    category: 'laptop',
    name: 'Alienware 16 Aurora',
    price: 132789.98,
    url: 'https://www.dell.com/en-in/shop/gaming-and-games/alienware-16-aurora-gaming-laptop/spd/alienware-aurora-ac16250-gaming-laptop/oan1625000901mino',
    imageUrl: 'https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/alienware-notebooks/alienware-16-r2-intel/media-gallery/black/notebook-alienware-16-r2-gallery-black-1.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=550&qlt=100,1&resMode=sharp2&size=550,402&chrss=full',
    dataAiHint: 'alienware laptop',
    specs: [
      { name: 'CPU', value: 'Intel Core i7', icon: 'Cpu' },
      { name: 'GPU', value: 'NVIDIA RTX 4060', icon: 'Component' },
      { name: 'RAM', value: '16GB DDR5', icon: 'MemoryStick' },
      { name: 'Storage', value: '1TB SSD', icon: 'HardDrive' },
      { name: 'Display', value: '16" QHD+ 240Hz', icon: 'Laptop' },
    ],
  },
];

export const peripheralData: Product[] = [
  {
    id: 'thinkvision-m14t',
    category: 'peripheral',
    name: 'ThinkVision M14t Gen 2',
    price: 29990.0,
    url: 'https://www.lenovo.com/in/en/p/accessories-and-software/monitors/office/63fduar6ww',
    imageUrl: 'https://p2-ofp.static.pub/fes/cms/2023/07/11/gky7zbd6sgz1w5b1g1n8p4o1d0p39v716613.png',
    dataAiHint: 'portable monitor',
    specs: [
      { name: 'Type', value: 'Portable Monitor', icon: 'Monitor' },
      { name: 'Size', value: '14 inch Touch', icon: 'MonitorSmartphone' },
      { name: 'Resolution', value: '2240x1400', icon: 'Maximize' },
      { name: 'Refresh Rate', value: '60Hz', icon: 'RefreshCw' },
    ],
    emi: {
      12: 2664.58,
      18: 1828.85,
      24: 1411.73,
    },
  },
  {
    id: 'razer-basilisk-v3',
    category: 'peripheral',
    name: 'Razer Basilisk V3 Pro',
    price: 12000.0,
    url: 'https://amzn.in/d/8uCb0lI',
    imageUrl: 'https://assets3.razerzone.com/gY9bmyG4gY6fJc3Y1j8aPjIuY_4=/1500x1000/https/media.razer.com/bli/razer-basilisk-v3-pro-white-1500x1000-1.png',
    dataAiHint: 'gaming mouse',
    specs: [
        { name: 'Type', value: 'Wireless Mouse', icon: 'Mouse' },
        { name: 'Sensor', value: 'Optical', icon: 'Scan' },
        { name: 'DPI', value: '30,000', icon: 'Gauge' },
        { name: 'Buttons', value: '11 Programmable', icon: 'RectangleHorizontal' },
    ],
    emi: {
      12: 1066.19,
      18: 731.78,
      24: 564.88,
    },
  },
  {
    id: 'hive65-keyboard',
    category: 'peripheral',
    name: 'Hive65 Mechanical Keyboard',
    price: 3000.0,
    url: 'https://kreo-tech.com/collections/keys-to-victory/products/hive65-mechanical-gaming-keyboard-with-kreo-purple-switches',
    imageUrl: 'https://kreo-tech.com/cdn/shop/files/Hive65BlackListingImage1_1_1800x1800.jpg?v=1720529555',
    dataAiHint: 'mechanical keyboard',
    specs: [
        { name: 'Type', value: 'Mechanical Keyboard', icon: 'Keyboard' },
        { name: 'Switch', value: 'Kreo Purple Switches', icon: 'ToggleLeft' },
        { name: 'Layout', value: '65% Compact', icon: 'LayoutGrid' },
        { name: 'Backlight', value: 'RGB', icon: 'Zap' },
    ],
    emi: {
      12: 266.55,
      18: 182.95,
      24: 141.22,
    },
  },
  {
    id: 'arctik-cooler',
    category: 'peripheral',
    name: 'Arctik Laptop Cooler',
    price: 3000.0,
    url: 'https://kreo-tech.com/products/arctik-laptop-cooler',
    imageUrl: 'https://kreo-tech.com/cdn/shop/files/ArtikListing1_1_1800x1800.jpg?v=1720529124',
    dataAiHint: 'laptop cooler',
    specs: [
        { name: 'Type', value: 'Cooling Pad', icon: 'Fan' },
        { name: 'Fan Speed', value: 'Up to 2400 RPM', icon: 'Gauge' },
        { name: 'Noise Level', value: '25 dBA', icon: 'Volume2' },
        { name: 'Lighting', value: 'RGB', icon: 'Zap' },
    ],
    emi: {
      12: 266.55,
      18: 182.95,
      24: 141.22,
    },
  },
];
